### ISSUE TITLE
userinfo_url in configuration

### ISSUE THREAD

**Issue by rflaperuta** [Rukenshia/ueberauth_keycloak#1]
Hello!

I'm using `Confex` for resolving configuration in runtime. But, I'm having a hard time setting the `userinfo_url` parameter. It is too deeply nested for it.

What about moving it to be together with the `authorize_url` and `token_url`?

Thx

**Comment by Rukenshia** [comment]
Hi!

thanks for raising this. I don't really work on the project this was used for anymore, were you thinking about creating a PR for this? The request sounds absolutely reasonable.
Otherwise I could work on it when I get time for it.

Cheers,

**Comment by rflaperuta** [comment]
Sounds like a great opportunity, I'll give a try at it! :-)

**Comment by Rukenshia** [comment]
Merged via #2 . Thanks a lot for your contribution!
