### ISSUE TITLE
Invalid Token Error

### ISSUE THREAD

**Issue by soyPabloG** [Rukenshia/ueberauth_keycloak#5]
When fetching `userinfo` endpoint, KeyCloak responses invalid token error:
```
[error] #PID<0.892.0> running App.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /auth/keycloak/callback?session_state=...&code=...
** (exit) {%CaseClauseError{term: {:error, %OAuth2.Response{body: %{"error" => "invalid_token", "error_description" => "Token verification failed"}, headers: [{"x-xss-protection", "1; mode=block"}, {"x-frame-options", "SAMEORIGIN"}, {"referrer-policy", "no-referrer"}, {"date", "Tue, 21 Sep 2021 19:43:11 GMT"}, {"connection", "keep-alive"}, {"www-authenticate", "Bearer realm=\"myrealm\", error=\"invalid_token\", error_description=\"Token verification failed\""}, {"strict-transport-security", "max-age=31536000; includeSubDomains"}, {"x-content-type-options", "nosniff"}, {"content-type", "application/json"}, {"content-length", "73"}], status_code: 401}}}, []}
```
Apparently `clientId` and `userId` are not being sended (KeyCloak logs shows):
```
19:43:11,669 WARN  [org.keycloak.events] (default task-12) type=USER_INFO_REQUEST_ERROR, realmId=myrealm, clientId=null, userId=null, ipAddress=172.17.0.1, error=invalid_token, auth_method=validate_access_token
```

**Comment by Rukenshia** [comment]
Hi!

I have not actively worked with this provider for quite some time, but can you share your configuration? I'll try to take a look at it - if you think you can debug and fix this for yourself if it ends up being an issue with the strategy, pull requests are more than welcome!

**Comment by soyPabloG** [comment]
Sure! This is the setup of the client:
```
{
  "realm": "myrealm",
  "auth-server-url": "http://localhost:8080/auth/",
  "ssl-required": "external",
  "resource": "discuss",
  "verify-token-audience": true,
  "credentials": {
    "secret": "..."
  },
  "use-resource-role-mappings": true,
  "confidential-port": 0
}
```
And this is the configuration on Phoenix:
```elixir
config :ueberauth, Ueberauth,
  providers: [
    keycloak: {Ueberauth.Strategy.Keycloak, [default_scope: "openid"]}
  ]

config :ueberauth, Ueberauth.Strategy.Keycloak.OAuth,
  client_id: "discuss",
  authorize_url: "http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth",
  token_url: "http://docker.for.mac.host.internal:8080/auth/realms/myrealm/protocol/openid-connect/token",
  userinfo_url: "http://docker.for.mac.host.internal:8080/auth/realms/myrealm/protocol/openid-connect/userinfo",
  client_secret: "...",
  redirect_uri: "http://localhost:4000/auth/keycloak/callback"
```

I think that the problem are the parameters passed to `http://docker.for.mac.host.internal:8080/auth/realms/myrealm/protocol/openid-connect/userinfo`, but I can't found how to test it 🤔. I'm using two containers connected to my host network (that's why url is `docker.for.mac.host.internal`), but they can reach each other properly.

**Comment by kkentzo** [comment]
I had similar problems with invalid token errors (related to the absence of a serialized for `oauth2`) so perhaps #6 (which is now in master) could be of help (or not).

For troubleshooting you could try [setting `oauth2` in debug mode](https://hexdocs.pm/oauth2/readme.html#debug-mode) and inspect the requests and responses .

**Comment by Rukenshia** [comment]
@soyPabloG were you able to resolve the problem?
